title: Hello, world! I'm Khalid Hussain
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink:
baseurl:  
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Khalid Hussain # add your name
author-img: david-freeman.jpg # add your photo
about-author: Unstoppable learner @Enterprise Security (XaaS) # add description
social-twitter:https://twitter.com/xkhahuss # add your Twitter handle
social-facebook: https://www.facebook.com/xkhahuss # add your Facebook handle
social-github: xkhahuss # add your Github handle
social-linkedin:https://www.linkedin.com/in/xkhahuss/ # add your Linkedin handle
social-email: xkhahuss@hotmail.com # add your Email address

# Disqus
discus-identifier: 
# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
